spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/evently}
    username: ${DB_USERNAME:evently_user}
    password: "${DB_PASSWORD:ChangeMe_Strong_#2025}"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
