spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
  flyway:
    enabled: true
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
server:
  forward-headers-strategy: framework

app:
  cors:
    origins: ${APP_CORS_ORIGINS:*}
