package com.evently.dto;

import com.evently.domain.Role;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateUserRequest {
    @Email
    @NotBlank
    private String email;

    @NotBlank
    private String name;

    private Role role; // optional

    // getters/setters generated by Lombok @Data
}
